### ISSUE TITLE
Still actif ? 

### ISSUE THREAD

**Issue by Distrib-ps** [FullLifeGames/BattleHelper#17]
Is the project still in progress? Because : http://prntscr.com/w0i2xi
http://prntscr.com/w0mruc
Thx!

**Comment by FullLifeGames** [comment]
This is still maintained, but I couldn't replicated your issue.

Since this might've been a temporary issue, it would be good if you could try again!

Edit: Could you maybe also provide the mode you were searching in?

**Comment by Distrib-ps** [comment]
Ah! It works now! Thank you !
